name: Build DevNEwsBot CLI Image

on:
  push:
    branches:    
      - main
      - 'release/**'
    tags:        
      - v1
      - v1.*
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 8.0.x
      - name: Restore Tools
        run: dotnet tool restore
      - name: Restore dependencies
        run: dotnet restore
      #    - name: Run .NET Code Analysis
      #      uses: dotnet/code-analysis@main
      #      id: code-analysis
      #      with:
      #        build-breaking: true
      #        style: minimum
      #        dotnet-version: '6.0.x'
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build
    