name: Build DevNEwsBot CLI Image

on:
  push:
    branches:    
      - main
      - 'release/**'
    tags:        
      - v1
      - v1.*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.21'
        check-latest: true
        cache: true

    - name: Build
      run: make build

    - name: Test
      run: make test
    - name: Go Vet
      run: make vet
      
    - uses: dominikh/staticcheck-action@v1.3.0
      name: staticcheck
      with:
        version: "2023.1"
        install-go: false
    