name: Run Bot 

on:
  schedule:
    - cron: "00 11 * * 6,1,3,5"
env:
  ConnectionStrings__DiscordWebhookUrl: "${{ secrets.DISCORD_URL }}"
  ConnectionStrings__Games: "${{ secrets.MONGO_CONNECTION_STRING }}"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Restore Tools
        run: dotnet tool restore
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      
      - name: RUN
        run: | 
          cd src/XboxPromotionCheckerBot.App
          dotnet run 
